---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  The template is used to create a VPC with CIDR provided as parameter.

# Metadata:
#   template metadata

Parameters:
  VPC:
    Description: The ID of the VPC
    Type: String
  PublicSubnet:
    Description: The public subnet
    Type: String
  PrivateSubnet:
    Description: The private subnet 1
    Type: String
  secSSHJumpbox:
    Description: The secSSHJumpbox
    Type: String
  secSSHPrivate:
    Description: The secSSHJumpbox
    Type: String
  AZ:
    Description: The availability zone
    Type: String
  Environment:
    Description: The application environment
    Type: String

# Rules:
#   set of rules

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:
  jumpBoxEC2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: jumpbox
      ImageId: ami-09d3b3274b6c5d4aa
      InstanceType: t2.micro
      AvailabilityZone: !Ref AZ
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref secSSHJumpbox
      Tags:
        - Key: Name
          Value: !Join [ "-", [ "ec2",!Ref AZ,!Ref Environment,"jumpBox" ] ]
        - Key: Environment
          Value: !Ref Environment   

  webServerEc2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: jumpbox
      ImageId: ami-09d3b3274b6c5d4aa
      InstanceType: t2.micro
      AvailabilityZone: !Ref AZ
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref secSSHPrivate
      Tags:
        - Key: Name
          Value: !Join [ "-", [ "ec2",!Ref AZ,!Ref Environment,"webServer" ] ]
        - Key: Environment
          Value: !Ref Environment 

# Outputs:
#   set of outputs